---
version: 1
disable_existing_loggers: False
formatters:
  json:
    format: "%(asctime)s %(process)d %(name)s %(levelname)s %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json

  info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: logs/info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: json
      filename: logs/errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

root:
  level: INFO
  handlers: [console]
